### ISSUE TITLE
unable to upvote

### ISSUE THREAD

**Issue by AbhishekSharma102** [berkmancenter/question_tool#61] opened 2017-03-09 04:19 UTC
Hey, there seems to be an issue during upvoting by users other than the one who created the question. Can someone have a look at that? Thanks

**Comment by mariamrf** [comment] 2017-03-09 08:03
Can you describe the issue in more detail? Votes are only allowed once per IP and per account. If it behaves differently, please describe how.

**Comment by AbhishekSharma102** [comment] 2017-03-09 08:22
there is an issue if multiple logged in users are connected to the same ip and try to upvote, only one would be able to successfully upvote. This is typical in the work environment for this tool, as multiple students/others would probably be connected to the same wireless/wired network

**Comment by mariamrf** [comment] 2017-03-09 15:16
This is true if the tool is not deployed on the same network as well, yes. But there remains the problem of multiple votes per person if that person is not logged in (or they voted while logged in, then logged out and voted again. Or if they created multiple accounts instantaneously to vote multiple times) if votes are only tied to logged in accounts. If it's tied to cookies + account if logged in then it's slightly better but one could easily remove all cookies and vote again. What do you suggest could be the solution to this? We want to ensure, as much as possible, that each person only votes once and can't really work around it easily (we also want non-logged-in users to be able to vote).

**Comment by arshdkhn1** [comment] 2017-03-09 15:33
@blaringsilence you can save the id of user in a  `userVotedList` kinda variable in your question model and then for each vote submission check whether that user has voted or not. I also faced a similar issue while making a voting app, i haven't fixed it though.

**Comment by mariamrf** [comment] 2017-03-09 15:36
@arshdkhn1 we do check against users who already voted for this question but:

1. We want non-logged in users to be able to vote and also vote once.
2. We want to minimize multiple voting by methods of new account creation, clearing the cookies, etc.

**Comment by ar5had** [comment] 2017-03-09 15:43
Oops I accidently deleted the previous comment. @blaringsilence while making my voting app, the only way I found out to stop multiple voting is to check user against a fixed variable. One option that I thought was MAC Address, but MAC Address can't be fetched on web. Till now, I haven't been able to find a solid method to implement this. I will post my idea, if I find one.

**Comment by AbhishekSharma102** [comment] 2017-03-09 17:17
@blaringsilence @arshdkhn1 Hey, i think it would be better to use device details along with ip and cookies for blocking anonymous users. Though we wont be able to distinguish between two people with similar devices, but it still is better than just ip and cookies. I'll try to find a better solution, but i think this could work.

**Comment by ar5had** [comment] 2017-03-09 17:20
@AbhishekSharma102 The problem is one can easily revote by clearing cookies or browsing in private mode.

**Comment by mariamrf** [comment] 2017-03-09 17:31
So here's what we can get/use when someone attempts to upvote and the server is deciding whether or not to register said vote:
- Client's IP address
- Anything else that is already in our database (for example: if logged in, all user info, etc)

We can't get any other "device details" that are in any way specific to a single user.

We don't use cookies at the moment, because:
- You can just clear cookies and re-vote.
- You can browse in private mode and re-vote (repeat however many times you want).

What we use right now (some of this might not be visible at the moment as it hasn't been merged yet):
- One vote per IP.
- One vote per user.

So if the very first vote is from logged in user X and IP 1.1.1.1, later on if user X tries to re-vote while logged in (on any device) that wouldn't work, and if they try to re-vote on the same device, whether logged in or not, that wouldn't work wither.

And if user Y is not logged in (anon), only the IP is stored. So if anyone with that IP tries to vote again, it wouldn't work, regardless of being logged in.

**Comment by AbhishekSharma102** [comment] 2017-03-09 17:48
We can detect platform specifications like operating system, browser version, etc. and use that to reduce the number of people we block. Another idea would be to block users from upvoting while browsing in incognito mode. So, if a person tries to upvote the same question again from same device(or a device with similar specification), we can stop them from upvoting. There are libraries like fingerprintjs that can be used in this situation.

**Comment by mariamrf** [comment] 2017-03-09 18:27
From the fingerprintjs readme:

> Then these values are passed through a hashing function to produce a fingerprint that gives **weak guarantees of uniqueness**.

also

> It's worth noting that a **mobile share of browsers is much more uniform**.

And I agree; it can't be actually unique. OS, browser version, etc are good for figuring out your demographic and for serving a compatible version of your app, but they shouldn't be used to identify a user.

**Comment by AbhishekSharma102** [comment] 2017-03-09 19:24
I agree with you. So there is no way other than blocking the entire ip?

**Comment by mariamrf** [comment] 2017-03-09 19:40
At the moment I can't think of anything else, but I'm open to suggestions always.

**Closed as completed** 2017-03-09 20:40 UTC
